from flask import Flask, render_template, request, make_response
import requests
import gyfe
import io
app = Flask(__name__)

session = None #Will be generated by new SessionManager
args = None #Will be taken from user

@app.route('/get_csv')
def get_csv():
    if args.electives == "breadth":
        file = gyfe.save_breadths(args, session, False)
    elif args.electives == "depth":
        file = gyfe.save_depths(args, session, False)
    
    buffer = io.StringIO()
    buffer.write(file)
    buffer.seek(0)
    
    response = make_response(buffer.getvalue())
    response.headers['Content-Disposition'] = 'attachment; filename=data.csv'
    response.headers['Content-Type'] = 'text/csv'
    
    return response
    
    
    
    
